# Generated by Django 4.1.5 on 2023-01-20 06:19

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SomeString',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, null=True, verbose_name='Обновлено')),
                ('string', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'Строка',
                'verbose_name_plural': 'Строки',
            },
        ),
    ]
